"""Add timestamp column to Interaccion

Revision ID: 1158605d5fbd
Revises: 
Create Date: 2024-06-02 04:49:52.417699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1158605d5fbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarioservicio')
    op.drop_table('registroservicio')
    with op.batch_alter_table('interaccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.alter_column('mensaje_usuario',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('respuesta_bot',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('fecha_hora')

    with op.batch_alter_table('registro_usuario', schema=None) as batch_op:
        batch_op.alter_column('tiempo_fin',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.drop_constraint('repuesto_ibfk_1', type_='foreignkey')
        batch_op.drop_column('servicio_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('repuesto_ibfk_1', 'servicio', ['servicio_id'], ['id'])
        batch_op.alter_column('precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('registro_usuario', schema=None) as batch_op:
        batch_op.alter_column('tiempo_fin',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('interaccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_hora', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False))
        batch_op.alter_column('respuesta_bot',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('mensaje_usuario',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('timestamp')

    op.create_table('registroservicio',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tiempo_inicio', mysql.DATETIME(), nullable=False),
    sa.Column('tiempo_fin', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='registroservicio_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_spanish_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('comentarioservicio',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('servicio_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comentario', mysql.TEXT(), nullable=False),
    sa.Column('analisis_sentimiento', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_hora', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], name='comentarioservicio_ibfk_2'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='comentarioservicio_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_spanish_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
